### ISSUE TITLE
I have a problem displaying img and msk.

### ISSUE THREAD

**Issue by nguyenduongZ** [KhoiDOO/ibla#8]
In CustomBagls, __init__ function, I don't use self.aug_transforms, but img and msk don't match. When Custom follows the dataset Drive, it outputs correctly.
![image](https://github.com/KhoiDOO/ibla/assets/116706467/f3d8d5ee-e2ab-4247-ae16-306b0784687d)

**Comment by KhoiDOO** [comment]
If you have figured it out I gonna close this issue.
